# Generated by Django 3.1.7 on 2021-02-24 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barberos',
            fields=[
                ('idBarbero', models.AutoField(primary_key=True, serialize=False)),
                ('detalle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('idCatalogo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('0', 'Servicios'), ('1', 'Productos')], default='0', max_length=1)),
                ('detalle', models.CharField(max_length=100)),
                ('valor', models.FloatField()),
                ('foto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=50, unique=True)),
                ('contrasena', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('idReserva', models.AutoField(primary_key=True, serialize=False)),
                ('fechaHoraReserva', models.DateTimeField()),
                ('idBarbero', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='barberia.barberos')),
                ('idCatalogo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='barberia.catalogo')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='barberia.usuarios')),
            ],
        ),
        migrations.AddField(
            model_name='barberos',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='barberia.usuarios'),
        ),
    ]
