# Generated by Django 3.1.7 on 2021-04-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberia', '0002_usuarios_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo',
            name='foto',
            field=models.ImageField(upload_to='none'),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='tipo',
            field=models.CharField(choices=[('0', 'Servicio'), ('1', 'Producto')], default='0', max_length=1),
        ),
    ]
