# Generated by Django 3.1.7 on 2021-04-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberia', '0003_auto_20210427_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo',
            name='valor',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
